permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: MurphyNeo
  email: murphyneo@163.com
  link: http://murphyneo.github.io
  weibo: http://murphyneo.github.io
  github: http://github.com/MurphyNeo

# 站点信息
title: MurphyNeo's Blog 
description: MurphyNeo's Blog
url: http://murphyneo.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
ga:
  id: UA-54767140-1
  url: http://murphyneo.github.io

# disqus 设置
disqus:
  shortname: murphyneo