permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

markdown: redcarpet
redcarpet:
	extensions:["fenced_code_blocks", "autolink", "tables", "strikethrough"]

# 作者信息
author: 
  name: MurphyNeo
  email: murphyneo@163.com
  link: http://murphyneo.github.io
  weibo: http://murphyneo.github.io
  github: http://github.com/MurphyNeo

# 站点信息
title: MurphyNeo's Blog 
description: MurphyNeo's Blog
url: http://murphyneo.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://murphyneo.github.io/thumb_IMG_0738_1024.jpg
favicon: http://murphyneo.github.io/thumb_IMG_0738_1025.jpg

# google analytics 设置
ga:
  id: UA-54767140-1
  url: http://murphyneo.github.io

# disqus 设置
disqus:
  shortname: murphyneo